version: "3.7"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    env_file: ./.env.development
    volumes:
      - polls_pg_data:/bitnami/postgresql

volumes:
  polls_pg_data:
